Cheetah Software: PeriodicTask Class Reference
PeriodicTask Class Reference abstract
#include <PeriodicTask.h>
Public Member Functions
PeriodicTask (PeriodicTaskManager *taskManager, float period, std::string name)
void start ()
void stop ()
void printStatus ()
void clearMax ()
bool isSlow ()
virtual void init ()=0
virtual void run ()=0
virtual void cleanup ()=0
virtual ~PeriodicTask ()
float getPeriod ()
float getRuntime ()
float getMaxPeriod ()
float getMaxRuntime ()
Private Member Functions
void loopFunction ()
Private Attributes
float _period
volatile bool _running = false
float _lastRuntime = 0
float _lastPeriodTime = 0
float _maxPeriod = 0
float _maxRuntime = 0
std::string _name
std::thread _thread
Detailed Description
A single periodic task which will call run() at the given frequency
Definition at line 19 of file PeriodicTask.h.
Constructor & Destructor Documentation
PeriodicTask::PeriodicTask (PeriodicTaskManager * taskManager, float period, std::string name)
Definition at line 14 of file PeriodicTask.cpp.
References PeriodicTaskManager::addTask().
     : _period(period), _name(name) {
   taskManager->addTask(this);
 }
virtual PeriodicTask::~PeriodicTask () inline virtual
Definition at line 31 of file PeriodicTask.h.
References stop().
 { stop(); }
Member Function Documentation
virtual void PeriodicTask::cleanup () pure virtual
Implemented in PeriodicMemberFunction< T >, PrintTaskStatus, PeriodicFunction, RobotInterface, RobotRunner, and TestPeriodicTask.
void PeriodicTask::clearMax ()
Definition at line 48 of file PeriodicTask.cpp.
References _maxPeriod, and _maxRuntime.
{
   _maxPeriod = 0;
   _maxRuntime = 0;
 }
float PeriodicTask::getMaxPeriod () inline
Definition at line 37 of file PeriodicTask.h.
References _maxPeriod.
 { return _maxPeriod; }
float PeriodicTask::getMaxRuntime () inline
Definition at line 39 of file PeriodicTask.h.
References _maxRuntime, and loopFunction().
 { return _maxRuntime; }
float PeriodicTask::getPeriod () inline
Definition at line 33 of file PeriodicTask.h.
References _period.
 { return _period; }
float PeriodicTask::getRuntime () inline
Definition at line 35 of file PeriodicTask.h.
References _lastRuntime.
 { return _lastRuntime; }
virtual void PeriodicTask::init () pure virtual
Implemented in PeriodicMemberFunction< T >, PrintTaskStatus, PeriodicFunction, RobotInterface, RobotRunner, and TestPeriodicTask.
bool PeriodicTask::isSlow ()
Definition at line 44 of file PeriodicTask.cpp.
References _maxPeriod, _maxRuntime, and _period.
{
   return _maxPeriod > _period * 1.3f || _maxRuntime > _period;
 }
void PeriodicTask::loopFunction () private
Definition at line 65 of file PeriodicTask.cpp.
References _lastPeriodTime, _lastRuntime, _maxPeriod, _maxRuntime, _name, _period, _running, f(), Timer::getSeconds(), run(), and Timer::start().
{
   auto timerFd = timerfd_create(CLOCK_MONOTONIC, 0);
   int seconds = (int)_period;
   int nanoseconds = (int)(1e9 * std::fmod(_period, 1.f));
   Timer t;
   itimerspec timerSpec;
   timerSpec.it_interval.tv_sec = seconds;
   timerSpec.it_value.tv_sec = seconds;
   timerSpec.it_value.tv_nsec = nanoseconds;
   timerSpec.it_interval.tv_nsec = nanoseconds;
   timerfd_settime(timerFd, 0, &timerSpec, nullptr);
   unsigned long long missed = 0;
   printf("[PeriodicTask] Start %s (%d s, %d ns)\n", _name.c_str(), seconds,
          nanoseconds);
   while (_running) {
     _lastPeriodTime = (float)t.getSeconds();
     t.start();
     run();
     _lastRuntime = (float)t.getSeconds();
     int m = read(timerFd, &missed, sizeof(missed));
     (void)m;
     _maxPeriod = std::max(_maxPeriod, _lastPeriodTime);
     _maxRuntime = std::max(_maxRuntime, _lastRuntime);
   }
   printf("[PeriodicTask] %s has stopped!\n", _name.c_str());
 }
void PeriodicTask::printStatus ()
Definition at line 53 of file PeriodicTask.cpp.
References _lastPeriodTime, _lastRuntime, _maxPeriod, _maxRuntime, _name, _period, _running, isSlow(), printf_color(), and Red.
{
   if (!_running) return;
   if (isSlow()) {
     printf_color(PrintColor::Red, "|%-20s|%6.4f|%6.4f|%6.4f|%6.4f|%6.4f\n",
                  _name.c_str(), _lastRuntime, _maxRuntime, _period,
                  _lastPeriodTime, _maxPeriod);
   } else {
     printf("|%-20s|%6.4f|%6.4f|%6.4f|%6.4f|%6.4f\n", _name.c_str(),
            _lastRuntime, _maxRuntime, _period, _lastPeriodTime, _maxPeriod);
   }
 }
virtual void PeriodicTask::run () pure virtual
Implemented in PeriodicMemberFunction< T >, PrintTaskStatus, PeriodicFunction, RobotInterface, RobotRunner, and TestPeriodicTask.
void PeriodicTask::start ()
Definition at line 20 of file PeriodicTask.cpp.
References _name, _running, _thread, init(), and loopFunction().
{
   if (_running) {
     printf("[PeriodicTask] Tried to start %s but it was already running!\n",
            _name.c_str());
     return;
   }
   init();
   _running = true;
   _thread = std::thread(&PeriodicTask::loopFunction, this);
 }
void PeriodicTask::stop ()
Definition at line 31 of file PeriodicTask.cpp.
References _name, _running, _thread, and cleanup().
{
   if (!_running) {
     printf("[PeriodicTask] Tried to stop %s but it wasn't running!\n",
            _name.c_str());
     return;
   }
   _running = false;
   printf("[PeriodicTask] Waiting for %s to stop...\n", _name.c_str());
   _thread.join();
   printf("[PeriodicTask] Done!\n");
   cleanup();
 }
Member Data Documentation
float PeriodicTask::_lastPeriodTime = 0 private
Definition at line 47 of file PeriodicTask.h.
float PeriodicTask::_lastRuntime = 0 private
Definition at line 46 of file PeriodicTask.h.
float PeriodicTask::_maxPeriod = 0 private
Definition at line 48 of file PeriodicTask.h.
float PeriodicTask::_maxRuntime = 0 private
Definition at line 49 of file PeriodicTask.h.
std::string PeriodicTask::_name private
Definition at line 50 of file PeriodicTask.h.
float PeriodicTask::_period private
Definition at line 44 of file PeriodicTask.h.
volatile bool PeriodicTask::_running = false private
Definition at line 45 of file PeriodicTask.h.
std::thread PeriodicTask::_thread private
Definition at line 51 of file PeriodicTask.h.
The documentation for this class was generated from the following files:
PeriodicTask.h
PeriodicTask.cpp