Cheetah Software: MiniCheetahHardwareBridge Class Reference
MiniCheetahHardwareBridge Class Reference
#include <HardwareBridge.h>
Public Member Functions
MiniCheetahHardwareBridge (RobotController *)
void runSpi ()
void initHardware ()
void run ()
void abort (const std::string &reason)
void abort (const char *reason)
Public Member Functions inherited from HardwareBridge
HardwareBridge (RobotController *robot_ctrl)
void prefaultStack ()
void setupScheduler ()
void initError (const char *reason, bool printErrno=false)
void initCommon ()
~HardwareBridge ()
void handleGamepadLCM (const lcm::ReceiveBuffer *rbuf, const std::string &chan, const gamepad_lcmt *msg)
void handleInterfaceLCM ()
void handleControlParameter (const lcm::ReceiveBuffer *rbuf, const std::string &chan, const control_parameter_request_lcmt *msg)
void publishVisualizationLCM ()
void run_sbus ()
Private Attributes
VectorNavData _vectorNavData
lcm::LCM _spiLcm
Additional Inherited Members
Protected Attributes inherited from HardwareBridge
PeriodicTaskManager taskManager
PrintTaskStatus statusTask
GamepadCommand _gamepadCommand
VisualizationData _visualizationData
CheetahVisualization _mainCheetahVisualization
lcm::LCM _interfaceLCM
lcm::LCM _visualizationLCM
control_parameter_respones_lcmt _parameter_response_lcmt
SpiData _spiData
SpiCommand _spiCommand
bool _firstRun = true
RobotRunner * _robotRunner = nullptr
RobotControlParameters _robotParams
u64 _iterations = 0
std::thread _interfaceLcmThread
volatile bool _interfaceLcmQuit = false
ControlParameters * _userControlParameters = nullptr
int _port
Detailed Description
Definition at line 72 of file HardwareBridge.h.
Constructor & Destructor Documentation
MiniCheetahHardwareBridge::MiniCheetahHardwareBridge (RobotController * robot_ctrl)
Definition at line 201 of file HardwareBridge.cpp.
     : HardwareBridge(robot_ctrl), _spiLcm(getLcmUrl(255)) {}
Member Function Documentation
void MiniCheetahHardwareBridge::abort (const std::string & reason)
void MiniCheetahHardwareBridge::abort (const char * reason)
void MiniCheetahHardwareBridge::initHardware ()
Definition at line 275 of file HardwareBridge.cpp.
References _vectorNavData, init_spi(), init_vectornav(), HardwareBridge::initError(), and VectorNavData::quat.
{
   printf("[MiniCheetahHardware] Init vectornav\n");
   _vectorNavData.quat << 1, 0, 0, 0;
   if (!init_vectornav(&_vectorNavData)) {
     initError("failed to initialize vectornav!\n", false);
   }
   init_spi();
   // init spi
   // init sbus
   // init lidarlite
   // init LCM hardware logging thread
   //
 }
void MiniCheetahHardwareBridge::run ()
Definition at line 204 of file HardwareBridge.cpp.
References HardwareBridge::_firstRun, HardwareBridge::_gamepadCommand, HardwareBridge::_mainCheetahVisualization, HardwareBridge::_port, HardwareBridge::_robotParams, HardwareBridge::_robotRunner, HardwareBridge::_spiCommand, HardwareBridge::_spiData, HardwareBridge::_userControlParameters, _vectorNavData, HardwareBridge::_visualizationData, RobotRunner::cheetahMainVisualization, RobotRunner::controlParameters, RobotRunner::driverCommand, RobotRunner::init(), init_sbus(), HardwareBridge::initCommon(), initHardware(), ControlParameters::isFullyInitialized(), MINI_CHEETAH, HardwareBridge::publishVisualizationLCM(), RobotRunner::robotType, HardwareBridge::run_sbus(), runSpi(), RobotRunner::spiCommand, RobotRunner::spiData, PeriodicTask::start(), HardwareBridge::statusTask, HardwareBridge::taskManager, RobotRunner::vectorNavData, and RobotRunner::visualizationData.
{
   initCommon();
   initHardware();
   //_robotRunner = new RobotRunner(&taskManager, 0.001f, "robot-control");
   _robotRunner->driverCommand = &_gamepadCommand;
   _robotRunner->spiData = &_spiData;
   _robotRunner->spiCommand = &_spiCommand;
   _robotRunner->robotType = RobotType::MINI_CHEETAH;
   _robotRunner->vectorNavData = &_vectorNavData;
   _robotRunner->controlParameters = &_robotParams;
   _robotRunner->visualizationData = &_visualizationData;
   _robotRunner->cheetahMainVisualization = &_mainCheetahVisualization;
   while (!_robotParams.isFullyInitialized()) {
     printf("[Hardware Bridge] Waiting for robot parameters...\n");
     usleep(1000000);
   }
   if(_userControlParameters) {
     while (!_userControlParameters->isFullyInitialized()) {
       printf("[Hardware Bridge] Waiting for user parameters...\n");
       usleep(1000000);
     }
   }
   printf("[Hardware Bridge] Got all parameters, starting up!\n");
   _robotRunner->init();
   _firstRun = false;
   // init control thread
   statusTask.start();
   // spi Task start
   PeriodicMemberFunction<MiniCheetahHardwareBridge> spiTask(
       &taskManager, .002, "spi", &MiniCheetahHardwareBridge::runSpi, this);
   spiTask.start();
   // robot controller start
   _robotRunner->start();
   // visualization start
   PeriodicMemberFunction<MiniCheetahHardwareBridge> visualizationLCMTask(
       &taskManager, .0167, "lcm-vis",
       &MiniCheetahHardwareBridge::publishVisualizationLCM, this);
   visualizationLCMTask.start();
   // rc controller
   _port = init_sbus(false);  // Not Simulation
   PeriodicMemberFunction<HardwareBridge> sbusTask(
       &taskManager, .005, "rc_controller", &HardwareBridge::run_sbus, this);
   sbusTask.start();
   for (;;) {
     usleep(1000000);
     // printf("joy %f\n", _robotRunner->driverCommand->leftStickAnalog[0]);
   }
 }
void MiniCheetahHardwareBridge::runSpi ()
Definition at line 293 of file HardwareBridge.cpp.
References HardwareBridge::_spiCommand, HardwareBridge::_spiData, _spiLcm, get_spi_command(), get_spi_data(), and spi_driver_run().
{
   spi_command_t* cmd = get_spi_command();
   spi_data_t* data = get_spi_data();
   memcpy(cmd, &_spiCommand, sizeof(spi_command_t));
   spi_driver_run();
   memcpy(&_spiData, data, sizeof(spi_data_t));
   _spiLcm.publish("spi_data", data);
   _spiLcm.publish("spi_command", cmd);
 }
Member Data Documentation
lcm::LCM MiniCheetahHardwareBridge::_spiLcm private
Definition at line 83 of file HardwareBridge.h.
VectorNavData MiniCheetahHardwareBridge::_vectorNavData private
Definition at line 82 of file HardwareBridge.h.
The documentation for this class was generated from the following files:
HardwareBridge.h
HardwareBridge.cpp