Cheetah Software: Quadruped< T > Class Template Reference
Quadruped< T > Class Template Reference
#include <Quadruped.h>
Public Member Functions
FloatingBaseModel< T > buildModel ()
bool buildModel (FloatingBaseModel< T > &model)
std::vector< ActuatorModel< T > > buildActuatorModels ()
Vec3< T > getHipLocation (int leg)
Static Public Member Functions
static T getSideSign (int leg)
Public Attributes
EIGEN_MAKE_ALIGNED_OPERATOR_NEW RobotType _robotType
T _bodyLength
T _bodyWidth
T _bodyHeight
T _bodyMass
T _abadGearRatio
T _hipGearRatio
T _kneeGearRatio
T _abadLinkLength
T _hipLinkLength
T _kneeLinkLength
T _maxLegLength
T _motorKT
T _motorR
T _batteryV
T _motorTauMax
T _jointDamping
T _jointDryFriction
SpatialInertia< T > _abadInertia
SpatialInertia< T > _hipInertia
SpatialInertia< T > _kneeInertia
SpatialInertia< T > _abadRotorInertia
SpatialInertia< T > _hipRotorInertia
SpatialInertia< T > _kneeRotorInertia
SpatialInertia< T > _bodyInertia
Vec3< T > _abadLocation
Vec3< T > _abadRotorLocation
Vec3< T > _hipLocation
Vec3< T > _hipRotorLocation
Vec3< T > _kneeLocation
Vec3< T > _kneeRotorLocation
Detailed Description
template<typename T>
class Quadruped< T >
Representation of a quadruped robot's physical properties.
When viewed from the top, the quadruped's legs are:
FRONT 2 1 RIGHT 4 3 BACK
Definition at line 56 of file Quadruped.h.
Member Function Documentation
template<typename T > std::vector< ActuatorModel< T > > Quadruped< T >::buildActuatorModels ()
Definition at line 225 of file Quadruped.cpp.
{
   std::vector<ActuatorModel<T>> models;
   models.emplace_back(_abadGearRatio, _motorKT, _motorR, _batteryV,
                       _jointDamping, _jointDryFriction, _motorTauMax);
   models.emplace_back(_hipGearRatio, _motorKT, _motorR, _batteryV,
                       _jointDamping, _jointDryFriction, _motorTauMax);
   models.emplace_back(_kneeGearRatio, _motorKT, _motorR, _batteryV,
                       _jointDamping, _jointDryFriction, _motorTauMax);
   return models;
 }
template<typename T > FloatingBaseModel< T > Quadruped< T >::buildModel ()
Build a FloatingBaseModel of the quadruped
Definition at line 113 of file Quadruped.cpp.
References FloatingBaseModel< T >::addBase(), FloatingBaseModel< T >::addBody(), FloatingBaseModel< T >::addGroundContactBoxPoints(), FloatingBaseModel< T >::addGroundContactPoint(), spatial::createSXform(), FloatingBaseModel< T >::setGravity(), ori::X, ori::Y, and ori::Z.
{
   FloatingBaseModel<T> model;
   // we assume the cheetah's body (not including rotors) can be modeled as a
   // uniformly distributed box.
   Vec3<T> bodyDims(_bodyLength, _bodyWidth, _bodyHeight);
   // model.addBase(_bodyMass, Vec3<T>(0,0,0), rotInertiaOfBox(_bodyMass,
   // bodyDims));
   model.addBase(_bodyInertia);
   // add contact for the cheetah's body
   model.addGroundContactBoxPoints(5, bodyDims);
   const int baseID = 5;
   int bodyID = baseID;
   T sideSign = -1;
   Mat3<T> I3 = Mat3<T>::Identity();
   // loop over 4 legs
   for (int legID = 0; legID < 4; legID++) {
     // Ab/Ad joint
     //  int addBody(const SpatialInertia<T>& inertia, const SpatialInertia<T>&
     //  rotorInertia, T gearRatio,
     //              int parent, JointType jointType, CoordinateAxis jointAxis,
     //              const Mat6<T>& Xtree, const Mat6<T>& Xrot);
     bodyID++;
     Mat6<T> xtreeAbad = createSXform(I3, withLegSigns<T>(_abadLocation, legID));
     Mat6<T> xtreeAbadRotor =
         createSXform(I3, withLegSigns<T>(_abadRotorLocation, legID));
     if (sideSign < 0) {
       model.addBody(_abadInertia.flipAlongAxis(CoordinateAxis::Y),
                     _abadRotorInertia.flipAlongAxis(CoordinateAxis::Y),
                     _abadGearRatio, baseID, JointType::Revolute,
                     CoordinateAxis::X, xtreeAbad, xtreeAbadRotor);
     } else {
       model.addBody(_abadInertia, _abadRotorInertia, _abadGearRatio, baseID,
                     JointType::Revolute, CoordinateAxis::X, xtreeAbad,
                     xtreeAbadRotor);
     }
     // Hip Joint
     bodyID++;
     Mat6<T> xtreeHip =
         createSXform(coordinateRotation<T>(CoordinateAxis::Z, T(M_PI)),
                      withLegSigns<T>(_hipLocation, legID));
     Mat6<T> xtreeHipRotor =
         createSXform(coordinateRotation<T>(CoordinateAxis::Z, T(M_PI)),
                      withLegSigns<T>(_hipRotorLocation, legID));
     if (sideSign < 0) {
       model.addBody(_hipInertia.flipAlongAxis(CoordinateAxis::Y),
                     _hipRotorInertia.flipAlongAxis(CoordinateAxis::Y),
                     _hipGearRatio, bodyID - 1, JointType::Revolute,
                     CoordinateAxis::Y, xtreeHip, xtreeHipRotor);
     } else {
       model.addBody(_hipInertia, _hipRotorInertia, _hipGearRatio, bodyID - 1,
                     JointType::Revolute, CoordinateAxis::Y, xtreeHip,
                     xtreeHipRotor);
     }
     // add knee ground contact point
     model.addGroundContactPoint(bodyID, Vec3<T>(0, 0, -_hipLinkLength));
     // Knee Joint
     bodyID++;
     Mat6<T> xtreeKnee = createSXform(I3, _kneeLocation);
     Mat6<T> xtreeKneeRotor = createSXform(I3, _kneeRotorLocation);
     if (sideSign < 0) {
       model.addBody(_kneeInertia.flipAlongAxis(CoordinateAxis::Y),
                     _kneeRotorInertia.flipAlongAxis(CoordinateAxis::Y),
                     _kneeGearRatio, bodyID - 1, JointType::Revolute,
                     CoordinateAxis::Y, xtreeKnee, xtreeKneeRotor);
     } else {
       model.addBody(_kneeInertia, _kneeRotorInertia, _kneeGearRatio, bodyID - 1,
                     JointType::Revolute, CoordinateAxis::Y, xtreeKnee,
                     xtreeKneeRotor);
     }
     // add foot
     model.addGroundContactPoint(bodyID, Vec3<T>(0, 0, -_kneeLinkLength), true);
     sideSign *= -1;
   }
   Vec3<T> g(0, 0, -9.81);
   model.setGravity(g);
   return model;
 }
template<typename T> bool Quadruped< T >::buildModel (FloatingBaseModel< T > & model)
Build a FloatingBaseModel of the quadruped
Definition at line 21 of file Quadruped.cpp.
References FloatingBaseModel< T >::addBase(), FloatingBaseModel< T >::addBody(), FloatingBaseModel< T >::addGroundContactBoxPoints(), FloatingBaseModel< T >::addGroundContactPoint(), spatial::createSXform(), FloatingBaseModel< T >::setGravity(), ori::X, ori::Y, and ori::Z.
{
   // we assume the cheetah's body (not including rotors) can be modeled as a
   // uniformly distributed box.
   Vec3<T> bodyDims(_bodyLength, _bodyWidth, _bodyHeight);
   // model.addBase(_bodyMass, Vec3<T>(0,0,0), rotInertiaOfBox(_bodyMass,
   // bodyDims));
   model.addBase(_bodyInertia);
   // add contact for the cheetah's body
   model.addGroundContactBoxPoints(5, bodyDims);
   const int baseID = 5;
   int bodyID = baseID;
   T sideSign = -1;
   Mat3<T> I3 = Mat3<T>::Identity();
   // loop over 4 legs
   for (int legID = 0; legID < 4; legID++) {
     // Ab/Ad joint
     //  int addBody(const SpatialInertia<T>& inertia, const SpatialInertia<T>&
     //  rotorInertia, T gearRatio,
     //              int parent, JointType jointType, CoordinateAxis jointAxis,
     //              const Mat6<T>& Xtree, const Mat6<T>& Xrot);
     bodyID++;
     Mat6<T> xtreeAbad = createSXform(I3, withLegSigns<T>(_abadLocation, legID));
     Mat6<T> xtreeAbadRotor =
         createSXform(I3, withLegSigns<T>(_abadRotorLocation, legID));
     if (sideSign < 0) {
       model.addBody(_abadInertia.flipAlongAxis(CoordinateAxis::Y),
                     _abadRotorInertia.flipAlongAxis(CoordinateAxis::Y),
                     _abadGearRatio, baseID, JointType::Revolute,
                     CoordinateAxis::X, xtreeAbad, xtreeAbadRotor);
     } else {
       model.addBody(_abadInertia, _abadRotorInertia, _abadGearRatio, baseID,
                     JointType::Revolute, CoordinateAxis::X, xtreeAbad,
                     xtreeAbadRotor);
     }
     // Hip Joint
     bodyID++;
     Mat6<T> xtreeHip =
         createSXform(coordinateRotation<T>(CoordinateAxis::Z, T(M_PI)),
                      withLegSigns<T>(_hipLocation, legID));
     Mat6<T> xtreeHipRotor =
         createSXform(coordinateRotation<T>(CoordinateAxis::Z, T(M_PI)),
                      withLegSigns<T>(_hipRotorLocation, legID));
     if (sideSign < 0) {
       model.addBody(_hipInertia.flipAlongAxis(CoordinateAxis::Y),
                     _hipRotorInertia.flipAlongAxis(CoordinateAxis::Y),
                     _hipGearRatio, bodyID - 1, JointType::Revolute,
                     CoordinateAxis::Y, xtreeHip, xtreeHipRotor);
     } else {
       model.addBody(_hipInertia, _hipRotorInertia, _hipGearRatio, bodyID - 1,
                     JointType::Revolute, CoordinateAxis::Y, xtreeHip,
                     xtreeHipRotor);
     }
     // add knee ground contact point
     model.addGroundContactPoint(bodyID, Vec3<T>(0, 0, -_hipLinkLength));
     // Knee Joint
     bodyID++;
     Mat6<T> xtreeKnee = createSXform(I3, _kneeLocation);
     Mat6<T> xtreeKneeRotor = createSXform(I3, _kneeRotorLocation);
     if (sideSign < 0) {
       model.addBody(_kneeInertia.flipAlongAxis(CoordinateAxis::Y),
                     _kneeRotorInertia.flipAlongAxis(CoordinateAxis::Y),
                     _kneeGearRatio, bodyID - 1, JointType::Revolute,
                     CoordinateAxis::Y, xtreeKnee, xtreeKneeRotor);
     } else {
       model.addBody(_kneeInertia, _kneeRotorInertia, _kneeGearRatio, bodyID - 1,
                     JointType::Revolute, CoordinateAxis::Y, xtreeKnee,
                     xtreeKneeRotor);
     }
     // add foot
     model.addGroundContactPoint(bodyID, Vec3<T>(0, 0, -_kneeLinkLength), true);
     sideSign *= -1;
   }
   Vec3<T> g(0, 0, -9.81);
   model.setGravity(g);
   return true;
 }
template<typename T> Vec3<T> Quadruped< T >::getHipLocation (int leg) inline
Get location of the hip for the given leg in robot frame
Definition at line 83 of file Quadruped.h.
{
     assert(leg >= 0 && leg < 4);
     Vec3<T> pHip((leg == 0 || leg == 1) ? _abadLocation(0) : -_abadLocation(0),
                  (leg == 1 || leg == 3) ? _abadLocation(1) : -_abadLocation(1),
                  _abadLocation(2));
     return pHip;
   }
template<typename T> static T Quadruped< T >::getSideSign (int leg) inline static
Definition at line 74 of file Quadruped.h.
{
     const T sideSigns[4] = {-1, 1, -1, 1};
     assert(leg >= 0 && leg < 4);
     return sideSigns[leg];
   }
Member Data Documentation
template<typename T> T Quadruped< T >::_abadGearRatio
Definition at line 61 of file Quadruped.h.
template<typename T> SpatialInertia<T> Quadruped< T >::_abadInertia
Definition at line 66 of file Quadruped.h.
template<typename T> T Quadruped< T >::_abadLinkLength
Definition at line 62 of file Quadruped.h.
template<typename T> Vec3<T> Quadruped< T >::_abadLocation
Definition at line 68 of file Quadruped.h.
template<typename T> SpatialInertia<T> Quadruped< T >::_abadRotorInertia
Definition at line 66 of file Quadruped.h.
template<typename T> Vec3<T> Quadruped< T >::_abadRotorLocation
Definition at line 68 of file Quadruped.h.
template<typename T> T Quadruped< T >::_batteryV
Definition at line 63 of file Quadruped.h.
template<typename T> T Quadruped< T >::_bodyHeight
Definition at line 60 of file Quadruped.h.
template<typename T> SpatialInertia<T> Quadruped< T >::_bodyInertia
Definition at line 66 of file Quadruped.h.
template<typename T> T Quadruped< T >::_bodyLength
Definition at line 60 of file Quadruped.h.
template<typename T> T Quadruped< T >::_bodyMass
Definition at line 60 of file Quadruped.h.
template<typename T> T Quadruped< T >::_bodyWidth
Definition at line 60 of file Quadruped.h.
template<typename T> T Quadruped< T >::_hipGearRatio
Definition at line 61 of file Quadruped.h.
template<typename T> SpatialInertia<T> Quadruped< T >::_hipInertia
Definition at line 66 of file Quadruped.h.
template<typename T> T Quadruped< T >::_hipLinkLength
Definition at line 62 of file Quadruped.h.
template<typename T> Vec3<T> Quadruped< T >::_hipLocation
Definition at line 68 of file Quadruped.h.
template<typename T> SpatialInertia<T> Quadruped< T >::_hipRotorInertia
Definition at line 66 of file Quadruped.h.
template<typename T> Vec3<T> Quadruped< T >::_hipRotorLocation
Definition at line 68 of file Quadruped.h.
template<typename T> T Quadruped< T >::_jointDamping
Definition at line 65 of file Quadruped.h.
template<typename T> T Quadruped< T >::_jointDryFriction
Definition at line 65 of file Quadruped.h.
template<typename T> T Quadruped< T >::_kneeGearRatio
Definition at line 61 of file Quadruped.h.
template<typename T> SpatialInertia<T> Quadruped< T >::_kneeInertia
Definition at line 66 of file Quadruped.h.
template<typename T> T Quadruped< T >::_kneeLinkLength
Definition at line 62 of file Quadruped.h.
template<typename T> Vec3<T> Quadruped< T >::_kneeLocation
Definition at line 68 of file Quadruped.h.
template<typename T> SpatialInertia<T> Quadruped< T >::_kneeRotorInertia
Definition at line 66 of file Quadruped.h.
template<typename T> Vec3<T> Quadruped< T >::_kneeRotorLocation
Definition at line 68 of file Quadruped.h.
template<typename T> T Quadruped< T >::_maxLegLength
Definition at line 62 of file Quadruped.h.
template<typename T> T Quadruped< T >::_motorKT
Definition at line 63 of file Quadruped.h.
template<typename T> T Quadruped< T >::_motorR
Definition at line 63 of file Quadruped.h.
template<typename T> T Quadruped< T >::_motorTauMax
Definition at line 64 of file Quadruped.h.
template<typename T> EIGEN_MAKE_ALIGNED_OPERATOR_NEW RobotType Quadruped< T >::_robotType
Definition at line 59 of file Quadruped.h.
The documentation for this class was generated from the following files:
Quadruped.h
Quadruped.cpp