Cheetah Software: save_file.h File Reference
save_file.h File Reference
#include <Configuration.h>
#include <cppTypes.h>
#include <stdio.h>
#include <sys/stat.h>
#include <algorithm>
#include <fstream>
#include <iostream>
#include <list>
#include <string>
Functions
void cleaning_file (const std::string &folder_name, const std::string &file_name, std::string &full_ret_file)
void create_folder (const std::string &folder_name)
template<typename T >
void saveVector (const DVec< T > &_vec, const std::string &folder_name, const std::string &file_name)
template<typename T >
void saveVector (const Vec3< T > &_vec, const std::string &folder_name, const std::string &file_name)
template<typename T >
void saveVector (const std::vector< T > &_vec, const std::string &folder_name, const std::string &file_name)
template<typename T >
void saveVector (T *_vec, const std::string &folder_name, const std::string &file_name, int size)
template<typename T >
void saveValue (T _value, const std::string &folder_name, const std::string &file_name)
Variables
static std::list< std::string > gs_fileName_string
Function Documentation
void cleaning_file (const std::string & folder_name, const std::string & file_name, std::string & full_ret_file)
Definition at line 3 of file save_file.cpp.
References gs_fileName_string.
{
   full_ret_file = THIS_COM + folder_name + file_name;
   full_ret_file += ".txt";
   std::list<std::string>::iterator iter = std::find(
       gs_fileName_string.begin(), gs_fileName_string.end(), full_ret_file);
   if (gs_fileName_string.end() == iter) {
     gs_fileName_string.push_back(full_ret_file);
     remove(full_ret_file.c_str());
   }
 }
void create_folder (const std::string & folder_name)
Definition at line 16 of file save_file.cpp.
References folder_name.
{
   std::string full_path = THIS_COM + folder_name;
   if (mkdir(full_path.c_str(), S_IRWXU | S_IRWXG | S_IROTH | S_IXOTH) == -1) {
     if (errno == EEXIST) {
       // alredy exists
       // printf("%s is already exist\n", full_path.c_str());
     } else {
       // something else
       std::cout << "cannot create session name folder error:" << strerror(errno)
                 << std::endl;
       exit(0);
     }
   }
 }
template<typename T > void saveValue (T _value, const std::string & folder_name, const std::string & file_name)
Definition at line 69 of file save_file.h.
References cleaning_file().
{
   std::string full_file_name;
   cleaning_file(folder_name, file_name, full_file_name);
   std::ofstream savefile(full_file_name.c_str(), std::ios::app);
   savefile << _value << "\n";
   savefile.flush();
 }
template<typename T > void saveVector (const DVec< T > & _vec, const std::string & folder_name, const std::string & file_name)
Definition at line 22 of file save_file.h.
References cleaning_file().
{
   std::string full_file_name;
   cleaning_file(folder_name, file_name, full_file_name);
   std::ofstream savefile(full_file_name.c_str(), std::ios::app);
   for (int i(0); i < _vec.rows(); ++i) {
     savefile << _vec(i) << "\t";
   }
   savefile << "\n";
   savefile.flush();
 }
template<typename T > void saveVector (const Vec3< T > & _vec, const std::string & folder_name, const std::string & file_name)
Definition at line 36 of file save_file.h.
References saveVector().
{
   saveVector((DVec<T>)_vec, folder_name, file_name);
 }
template<typename T > void saveVector (const std::vector< T > & _vec, const std::string & folder_name, const std::string & file_name)
Definition at line 42 of file save_file.h.
References cleaning_file().
{
   std::string full_file_name;
   cleaning_file(folder_name, file_name, full_file_name);
   std::ofstream savefile(full_file_name.c_str(), std::ios::app);
   for (unsigned int i(0); i < _vec.size(); ++i) {
     savefile << _vec[i] << "\t";
   }
   savefile << "\n";
   savefile.flush();
 }
template<typename T > void saveVector (T * _vec, const std::string & folder_name, const std::string & file_name, int size)
Definition at line 56 of file save_file.h.
References cleaning_file().
{
   std::string full_file_name;
   cleaning_file(folder_name, file_name, full_file_name);
   std::ofstream savefile(full_file_name.c_str(), std::ios::app);
   for (int i(0); i < size; ++i) {
     savefile << _vec[i] << "\t";
   }
   savefile << "\n";
   savefile.flush();
 }
Variable Documentation
std::list<std::string> gs_fileName_string static
Definition at line 14 of file save_file.h.