Cheetah Software: ControlParameterRequest Struct Reference
ControlParameterRequest Struct Reference
#include <ControlParameterInterface.h>
Public Member Functions
std::string toString ()
Public Attributes
char name [CONTROL_PARAMETER_MAXIMUM_NAME_LENGTH]
u64 requestNumber = UINT64_MAX
ControlParameterValue value
ControlParameterValueKind parameterKind
ControlParameterRequestKind requestKind
Detailed Description
Definition at line 26 of file ControlParameterInterface.h.
Member Function Documentation
std::string ControlParameterRequest::toString () inline
Definition at line 34 of file ControlParameterInterface.h.
References controlParameterRequestKindToString(), controlParameterValueKindToString(), controlParameterValueToString(), GET_ROBOT_PARAM_BY_NAME, GET_USER_PARAM_BY_NAME, SET_ROBOT_PARAM_BY_NAME, and SET_USER_PARAM_BY_NAME.
{
     std::string result = "Request(" + std::to_string(requestNumber) + ") " +
                          controlParameterRequestKindToString(requestKind) +
                          " " +
                          controlParameterValueKindToString(parameterKind) +
                          " " + std::string(name) + " ";
     switch (requestKind) {
       case ControlParameterRequestKind::GET_USER_PARAM_BY_NAME:
         result += "user is: ";
         result += controlParameterValueToString(value, parameterKind);
         return result;
       case ControlParameterRequestKind::SET_USER_PARAM_BY_NAME:
         result += "user to: ";
         result += controlParameterValueToString(value, parameterKind);
         return result;
       case ControlParameterRequestKind::GET_ROBOT_PARAM_BY_NAME:
         result += "robot is: ";
         result += controlParameterValueToString(value, parameterKind);
         return result;
       case ControlParameterRequestKind::SET_ROBOT_PARAM_BY_NAME:
         result += "robot to: ";
         result += controlParameterValueToString(value, parameterKind);
         return result;
       default:
         return result + " unknown request type!";
     }
   }
Member Data Documentation
char ControlParameterRequest::name[CONTROL_PARAMETER_MAXIMUM_NAME_LENGTH]
Initial value:
=
      ""
Definition at line 27 of file ControlParameterInterface.h.
ControlParameterValueKind ControlParameterRequest::parameterKind
Definition at line 31 of file ControlParameterInterface.h.
ControlParameterRequestKind ControlParameterRequest::requestKind
Definition at line 32 of file ControlParameterInterface.h.
u64 ControlParameterRequest::requestNumber = UINT64_MAX
Definition at line 29 of file ControlParameterInterface.h.
ControlParameterValue ControlParameterRequest::value
Definition at line 30 of file ControlParameterInterface.h.
The documentation for this struct was generated from the following file:
ControlParameterInterface.h