Cheetah Software: test_periodic_tasks.cpp File Reference
test_periodic_tasks.cpp File Reference
#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include "Utilities/PeriodicTask.h"
Classes
class TestPeriodicTask
Functions
void inc_scount ()
TEST (PeriodicTask, test1)
Variables
static int scount = 0
Function Documentation
void inc_scount ()
Definition at line 26 of file test_periodic_tasks.cpp.
References scount.
 { scount++; }
TEST (PeriodicTask , test1)
Definition at line 28 of file test_periodic_tasks.cpp.
References TestPeriodicTask::_cleanedUp, TestPeriodicTask::_counter, TestPeriodicTask::_init, TestPeriodicTask::_slow, f(), inc_scount(), scount, PeriodicTask::start(), and PeriodicTaskManager::stopAll().
{
   PeriodicTaskManager taskManager;
   TestPeriodicTask task1(&taskManager, 0.01f, "test-task-1");
   TestPeriodicTask task2(&taskManager, 0.02f, "test-task-2");
   task1.start();
   task2.start();
   for (int i = 0; i < 10; i++) {
     // taskManager.printStatus();
     usleep(50000);
   }
   task1.start();
   task1.start();
   EXPECT_TRUE(task2._counter > 0);
   EXPECT_TRUE(task2._init);
   EXPECT_FALSE(task2._cleanedUp);
   EXPECT_TRUE(task2._counter > 0);
   EXPECT_TRUE(task2._init);
   EXPECT_FALSE(task2._cleanedUp);
   taskManager.stopAll();
   TestPeriodicTask task3(&taskManager, .01f, "slow-task");
   task3._slow = true;
   task3.start();
   for (int i = 0; i < 10; i++) {
     // taskManager.printStatus();
     usleep(50000);
   }
   taskManager.stopAll();
   taskManager.stopAll();
   PeriodicFunction pf(&taskManager, 0.01f, "func-test", &inc_scount);
   pf.start();
   usleep(100000);
   EXPECT_TRUE(scount > 0);
   printf("scount = %d\n", scount);
   // taskManager.stopAll(); test destructors cleaning things up instead
 }
Variable Documentation
int scount = 0 static
Definition at line 24 of file test_periodic_tasks.cpp.