Cheetah Software: GamepadCommand Struct Reference
GamepadCommand Struct Reference
#include <GamepadCommand.h>
Public Member Functions
GamepadCommand ()
void zero ()
void set (const gamepad_lcmt *lcmt)
void get (gamepad_lcmt *lcmt)
void applyDeadband (float f)
std::string toString ()
Public Attributes
bool leftBumper
bool rightBumper
bool leftTriggerButton
bool rightTriggerButton
bool back
bool start
bool a
bool b
bool x
bool y
bool leftStickButton
bool rightStickButton
bool logitechButton
Vec2< float > leftStickAnalog
Vec2< float > rightStickAnalog
float leftTriggerAnalog
float rightTriggerAnalog
Detailed Description
Definition at line 12 of file GamepadCommand.h.
Constructor & Destructor Documentation
GamepadCommand::GamepadCommand () inline
Definition at line 13 of file GamepadCommand.h.
References zero().
 { zero(); }
Member Function Documentation
void GamepadCommand::applyDeadband (float f) inline
The Logitech F310's seem to do a bad job of returning to zero exactly, so a deadband around zero is useful when integrating joystick commands
Definition at line 87 of file GamepadCommand.h.
References deadband(), and eigenDeadband().
{
     eigenDeadband(leftStickAnalog, f);
     eigenDeadband(rightStickAnalog, f);
     leftTriggerAnalog = deadband(leftTriggerAnalog, f);
     rightTriggerAnalog = deadband(rightTriggerAnalog, f);
   }
void GamepadCommand::get (gamepad_lcmt * lcmt) inline
Definition at line 62 of file GamepadCommand.h.
References a, b, back, leftBumper, leftStickButton, leftTriggerAnalog, leftTriggerButton, rightBumper, rightStickButton, rightTriggerAnalog, rightTriggerButton, start, x, and y.
{
     lcmt->leftBumper = leftBumper;
     lcmt->rightBumper = rightBumper;
     lcmt->leftTriggerButton = leftTriggerButton;
     lcmt->rightTriggerButton = rightTriggerButton;
     lcmt->back = back;
     lcmt->start = start;
     lcmt->a = a;
     lcmt->x = x;
     lcmt->b = b;
     lcmt->y = y;
     lcmt->leftStickButton = leftStickButton;
     lcmt->rightStickButton = rightStickButton;
     lcmt->leftTriggerAnalog = leftTriggerAnalog;
     lcmt->rightTriggerAnalog = rightTriggerAnalog;
     for (int i = 0; i < 2; i++) {
       lcmt->leftStickAnalog[i] = leftStickAnalog[i];
       lcmt->rightStickAnalog[i] = rightStickAnalog[i];
     }
   }
void GamepadCommand::set (const gamepad_lcmt * lcmt) inline
Definition at line 41 of file GamepadCommand.h.
{
     leftBumper = lcmt->leftBumper;
     rightBumper = lcmt->rightBumper;
     leftTriggerButton = lcmt->leftTriggerButton;
     rightTriggerButton = lcmt->rightTriggerButton;
     back = lcmt->back;
     start = lcmt->start;
     a = lcmt->a;
     x = lcmt->x;
     b = lcmt->b;
     y = lcmt->y;
     leftStickButton = lcmt->leftStickButton;
     rightStickButton = lcmt->rightStickButton;
     leftTriggerAnalog = lcmt->leftTriggerAnalog;
     rightTriggerAnalog = lcmt->rightTriggerAnalog;
     for (int i = 0; i < 2; i++) {
       leftStickAnalog[i] = lcmt->leftStickAnalog[i];
       rightStickAnalog[i] = lcmt->rightStickAnalog[i];
     }
   }
std::string GamepadCommand::toString () inline
Definition at line 94 of file GamepadCommand.h.
References boolToString(), and eigenToString().
{
     std::string result =
         "Result:\nleftBumper: " + boolToString(leftBumper) + "\n" +
         "rightBumper: " + boolToString(rightBumper) + "\n" +
         "leftTriggerButton: " + boolToString(leftTriggerButton) + "\n" +
         "rightTriggerButton: " + boolToString(rightTriggerButton) + "\n" +
         "back: " + boolToString(back) + "\n" + "start: " + boolToString(start) +
         "\n" + "a: " + boolToString(a) + "\n" + "b: " + boolToString(b) + "\n" +
         "x: " + boolToString(x) + "\n" + "y: " + boolToString(y) + "\n" +
         "leftStickButton: " + boolToString(leftStickButton) + "\n" +
         "rightStickButton: " + boolToString(rightStickButton) + "\n" +
         "leftTriggerAnalog: " + std::to_string(leftTriggerAnalog) + "\n" +
         "rightTriggerAnalog: " + std::to_string(rightTriggerAnalog) + "\n" +
         "leftStickAnalog: " + eigenToString(leftStickAnalog) + "\n" +
         "rightStickAnalog: " + eigenToString(rightStickAnalog) + "\n";
     return result;
   }
void GamepadCommand::zero () inline
Definition at line 21 of file GamepadCommand.h.
               {
     leftBumper = false;
     rightBumper = false;
     leftTriggerButton = false;
     rightTriggerButton = false;
     back = false;
     start = false;
     a = false;
     b = false;
     x = false;
     y = false;
     leftStickButton = false;
     rightStickButton = false;
     leftTriggerAnalog = 0;
     rightTriggerAnalog = 0;
     leftStickAnalog = Vec2<float>::Zero();
     rightStickAnalog = Vec2<float>::Zero();
   }
Member Data Documentation
bool GamepadCommand::a
Definition at line 15 of file GamepadCommand.h.
bool GamepadCommand::b
Definition at line 15 of file GamepadCommand.h.
bool GamepadCommand::back
Definition at line 15 of file GamepadCommand.h.
bool GamepadCommand::leftBumper
Definition at line 15 of file GamepadCommand.h.
Vec2<float> GamepadCommand::leftStickAnalog
Definition at line 18 of file GamepadCommand.h.
bool GamepadCommand::leftStickButton
Definition at line 15 of file GamepadCommand.h.
float GamepadCommand::leftTriggerAnalog
Definition at line 19 of file GamepadCommand.h.
bool GamepadCommand::leftTriggerButton
Definition at line 15 of file GamepadCommand.h.
bool GamepadCommand::logitechButton
Definition at line 15 of file GamepadCommand.h.
bool GamepadCommand::rightBumper
Definition at line 15 of file GamepadCommand.h.
Vec2<float> GamepadCommand::rightStickAnalog
Definition at line 18 of file GamepadCommand.h.
bool GamepadCommand::rightStickButton
Definition at line 15 of file GamepadCommand.h.
float GamepadCommand::rightTriggerAnalog
Definition at line 19 of file GamepadCommand.h.
bool GamepadCommand::rightTriggerButton
Definition at line 15 of file GamepadCommand.h.
bool GamepadCommand::start
Definition at line 15 of file GamepadCommand.h.
bool GamepadCommand::x
Definition at line 15 of file GamepadCommand.h.
bool GamepadCommand::y
Definition at line 15 of file GamepadCommand.h.
The documentation for this struct was generated from the following file:
GamepadCommand.h