Cheetah Software: Utilities_print.h File Reference
Utilities_print.h File Reference
#include <stdarg.h>
#include <stdio.h>
#include <iostream>
#include <string>
#include "cppTypes.h"
Enumerations
enum PrintColor {
PrintColor::Default, PrintColor::Red, PrintColor::Green, PrintColor::Yellow,
PrintColor::Blue, PrintColor::Magenta, PrintColor::Cyan
}
Functions
template<typename T >
std::string pretty_string (T vv)
template<typename T >
void pretty_print (DMat< T > const &mm, std::ostream &os, std::string const &title, std::string const &prefix="", bool vecmode=false, bool nonl=false)
template<typename T >
void pretty_print (Quat< T > const &vv, std::ostream &os, std::string const &title, std::string const &prefix="", bool nonl=false)
template<typename T >
void pretty_print (DVec< T > const &vv, std::ostream &os, std::string const &title, std::string const &prefix="", bool nonl=false)
template<typename T >
void pretty_print (D3Mat< T > const &vv, std::ostream &os, std::string const &title, std::string const &prefix="", bool nonl=false)
template<typename T >
void pretty_print (Mat3< T > const &vv, std::ostream &os, std::string const &title, std::string const &prefix="", bool nonl=false)
template<typename T >
void pretty_print (Mat6< T > const &vv, std::ostream &os, std::string const &title, std::string const &prefix="", bool nonl=false)
template<typename T >
void pretty_print (SVec< T > const &vv, std::ostream &os, std::string const &title, std::string const &prefix="", bool nonl=false)
template<typename T >
void pretty_print (Vec3< T > const &vv, std::ostream &os, std::string const &title, std::string const &prefix="", bool nonl=false)
template<typename T >
void pretty_print (Vec2< T > const &vv, std::ostream &os, std::string const &title, std::string const &prefix="", bool nonl=false)
template<typename T >
void pretty_print (const std::vector< T > &_vec, const char *title)
template<typename T >
void pretty_print (const T *_vec, const char *title, size_t size)
void printf_color (PrintColor color, const char *fmt,...)
void fprintf_color (PrintColor color, FILE *stream, const char *fmt,...)
Enumeration Type Documentation
enum PrintColor strong
Enumerator
Default
Red
Green
Yellow
Blue
Magenta
Cyan
Definition at line 123 of file Utilities_print.h.
 { Default, Red, Green, Yellow, Blue, Magenta, Cyan };
Function Documentation
void fprintf_color (PrintColor color, FILE * stream, const char * fmt, ...)
Definition at line 13 of file Utilities_print.cpp.
{
   auto color_id = (uint32_t)color;
   if (color_id) fprintf(stream, "\033[1;%dm", (uint32_t)color + 30);
   va_list args;
   va_start(args, fmt);
   vfprintf(stream, fmt, args);
   va_end(args);
   fprintf(stream, "\033[0m");
 }
template<typename T > void pretty_print (DMat< T > const & mm, std::ostream & os, std::string const & title, std::string const & prefix = "", bool vecmode = false, bool nonl = false)
Definition at line 24 of file Utilities_print.h.
References pretty_string().
{
   char const *nlornot("\n");
   if (nonl) {
     nlornot = "";
   }
   if (!title.empty()) {
     os << title << nlornot;
   }
   if ((mm.rows() <= 0) || (mm.cols() <= 0)) {
     os << prefix << " (empty)" << nlornot;
   } else {
     if (vecmode) {
       if (!prefix.empty()) os << prefix;
       for (int ir(0); ir < mm.rows(); ++ir) {
         os << pretty_string(mm.coeff(ir, 0));
       }
       os << nlornot;
     } else {
       for (int ir(0); ir < mm.rows(); ++ir) {
         if (!prefix.empty()) os << prefix;
         for (int ic(0); ic < mm.cols(); ++ic) {
           os << pretty_string(mm.coeff(ir, ic));
         }
         os << nlornot;
       }
     }
   }
 }
template<typename T > void pretty_print (Quat< T > const & vv, std::ostream & os, std::string const & title, std::string const & prefix = "", bool nonl = false)
Definition at line 57 of file Utilities_print.h.
References pretty_print().
{
   pretty_print((DMat<T> const &)vv, os, title, prefix, true, nonl);
 }
template<typename T > void pretty_print (DVec< T > const & vv, std::ostream & os, std::string const & title, std::string const & prefix = "", bool nonl = false)
Definition at line 63 of file Utilities_print.h.
References pretty_print().
{
   pretty_print((DMat<T> const &)vv, os, title, prefix, true, nonl);
 }
template<typename T > void pretty_print (D3Mat< T > const & vv, std::ostream & os, std::string const & title, std::string const & prefix = "", bool nonl = false)
Definition at line 69 of file Utilities_print.h.
References pretty_print().
{
   pretty_print((DMat<T> const &)vv, os, title, prefix, false, nonl);
 }
template<typename T > void pretty_print (Mat3< T > const & vv, std::ostream & os, std::string const & title, std::string const & prefix = "", bool nonl = false)
Definition at line 76 of file Utilities_print.h.
References pretty_print().
{
   pretty_print((DMat<T> const &)vv, os, title, prefix, false, nonl);
 }
template<typename T > void pretty_print (Mat6< T > const & vv, std::ostream & os, std::string const & title, std::string const & prefix = "", bool nonl = false)
Definition at line 82 of file Utilities_print.h.
References pretty_print().
{
   pretty_print((DMat<T> const &)vv, os, title, prefix, false, nonl);
 }
template<typename T > void pretty_print (SVec< T > const & vv, std::ostream & os, std::string const & title, std::string const & prefix = "", bool nonl = false)
Definition at line 88 of file Utilities_print.h.
References pretty_print().
{
   pretty_print((DMat<T> const &)vv, os, title, prefix, true, nonl);
 }
template<typename T > void pretty_print (Vec3< T > const & vv, std::ostream & os, std::string const & title, std::string const & prefix = "", bool nonl = false)
Definition at line 94 of file Utilities_print.h.
References pretty_print().
{
   pretty_print((DMat<T> const &)vv, os, title, prefix, true, nonl);
 }
template<typename T > void pretty_print (Vec2< T > const & vv, std::ostream & os, std::string const & title, std::string const & prefix = "", bool nonl = false)
Definition at line 100 of file Utilities_print.h.
References pretty_print().
{
   pretty_print((DMat<T> const &)vv, os, title, prefix, true, nonl);
 }
template<typename T > void pretty_print (const std::vector< T > & _vec, const char * title)
Definition at line 106 of file Utilities_print.h.
{
   printf("%s: ", title);
   for (size_t i(0); i < _vec.size(); ++i) {
     printf("% 6.4f, \t", _vec[i]);
   }
   printf("\n");
 }
template<typename T > void pretty_print (const T * _vec, const char * title, size_t size)
Definition at line 115 of file Utilities_print.h.
{
   printf("%s: ", title);
   for (size_t i(0); i < size; ++i) {
     printf("% 6.4f, \t", _vec[i]);
   }
   printf("\n");
 }
template<typename T > std::string pretty_string (T vv)
Definition at line 14 of file Utilities_print.h.
{
   static int const buflen(32);
   static char buf[buflen];
   memset(buf, 0, sizeof(buf));
   snprintf(buf, buflen - 1, "% 6.6f  ", vv);
   std::string str(buf);
   return str;
 }
void printf_color (PrintColor color, const char * fmt, ...)
Definition at line 3 of file Utilities_print.cpp.
{
   auto color_id = (uint32_t)color;
   if (color_id) printf("\033[1;%dm", (uint32_t)color + 30);
   va_list args;
   va_start(args, fmt);
   vprintf(fmt, args);
   va_end(args);
   printf("\033[0m");
 }