Cheetah Software: test_math.cpp File Reference
test_math.cpp File Reference
Test math functions.
#include "Math/Interpolation.h"
#include "Math/MathUtilities.h"
#include "cppTypes.h"
#include "gmock/gmock.h"
#include "gtest/gtest.h"
Functions
TEST (Math, InterpolateLinear)
TEST (Math, BezierInterpolationFirstDerivative)
TEST (Math, BezierInterpolationSecondDerivative)
Detailed Description
Test math functions.
Definition in file test_math.cpp.
Function Documentation
TEST (Math , InterpolateLinear)
Definition at line 13 of file test_math.cpp.
References almostEqual(), and Interpolate::lerp().
{
   Vec3<double> y0(1, 2, 3);
   Vec3<double> y1(6, 5, 4);
   Vec3<double> yInterpRef = y0 + 0.75 * (y1 - y0);
   Vec3<double> yInterp = Interpolate::lerp(y0, y1, 0.75);
   EXPECT_TRUE(almostEqual(yInterp, yInterpRef, .001));
 }
TEST (Math , BezierInterpolationFirstDerivative)
Definition at line 25 of file test_math.cpp.
References almostEqual(), Interpolate::cubicBezier(), and Interpolate::cubicBezierFirstDerivative().
{
   Vec3<double> y0(1, 2, 3);
   Vec3<double> y1(6, 5, 4);
   double dx = .00001;
   double x = 0.23;
   Vec3<double> yInterpX = Interpolate::cubicBezier(y0, y1, x);
   Vec3<double> yInterpXdx = Interpolate::cubicBezier(y0, y1, x + dx);
   Vec3<double> dyInterpDxRef = (yInterpXdx - yInterpX) / dx;
   Vec3<double> dyInterpDx = Interpolate::cubicBezierFirstDerivative(y0, y1, x);
   EXPECT_TRUE(almostEqual(dyInterpDx, dyInterpDxRef, .001));
   for (int i = 0; i < 3; i++) {
     EXPECT_TRUE(yInterpX(i) > y0(i) && yInterpX(i) < y1(i));
   }
 }
TEST (Math , BezierInterpolationSecondDerivative)
Definition at line 46 of file test_math.cpp.
References almostEqual(), Interpolate::cubicBezierFirstDerivative(), and Interpolate::cubicBezierSecondDerivative().
{
   Vec3<double> y0(1, 2, 3);
   Vec3<double> y1(6, 5, 4);
   double dx = .00001;
   double x = 0.23;
   Vec3<double> yInterpX = Interpolate::cubicBezierFirstDerivative(y0, y1, x);
   Vec3<double> yInterpXdx =
       Interpolate::cubicBezierFirstDerivative(y0, y1, x + dx);
   Vec3<double> dyInterpDxRef = (yInterpXdx - yInterpX) / dx;
   Vec3<double> dyInterpDx = Interpolate::cubicBezierSecondDerivative(y0, y1, x);
   EXPECT_TRUE(almostEqual(dyInterpDx, dyInterpDxRef, .001));
 }