Cheetah Software: filter< T > Class Template Reference
filter< T > Class Template Reference abstract
#include <filters.h>
Public Member Functions
filter (void)
virtual ~filter (void)
virtual void input (T input_value)=0
virtual T output (void)=0
virtual void clear (void)=0
Detailed Description
template<typename T>
class filter< T >
Definition at line 5 of file filters.h.
Constructor & Destructor Documentation
template<typename T > filter< T >::filter (void) inline
Definition at line 7 of file filters.h.
 {}
template<typename T > virtual filter< T >::~filter (void) inline virtual
Definition at line 8 of file filters.h.
References filter< T >::clear(), filter< T >::input(), and filter< T >::output().
 {}
Member Function Documentation
template<typename T > virtual void filter< T >::clear (void) pure virtual
Implemented in AverageFilter< T >, ff02_filter< T >, ff01_filter< T >, deriv_lp_filter< T >, moving_average_filter< T >, digital_lp_filter< T >, and butterworth_filter< T >.
template<typename T > virtual void filter< T >::input (T input_value) pure virtual
Implemented in AverageFilter< T >, ff02_filter< T >, ff01_filter< T >, deriv_lp_filter< T >, moving_average_filter< T >, digital_lp_filter< T >, and butterworth_filter< T >.
template<typename T > virtual T filter< T >::output (void) pure virtual
Implemented in AverageFilter< T >, ff02_filter< T >, ff01_filter< T >, deriv_lp_filter< T >, moving_average_filter< T >, digital_lp_filter< T >, and butterworth_filter< T >.
The documentation for this class was generated from the following file:
filters.h