Cheetah Software: JPosInitializer< T > Class Template Reference
JPosInitializer< T > Class Template Reference
#include <JPosInitializer.h>
Public Member Functions
JPosInitializer (T end_time)
~JPosInitializer ()
bool IsInitialized (LegController< T > *)
Private Member Functions
void _UpdateParam ()
void _UpdateInitial (const LegController< T > *ctrl)
Private Attributes
bool _b_first_visit
T _end_time
T _curr_time
T _dt
std::vector< T > _ini_jpos
std::vector< T > _target_jpos
std::vector< T > _mid_jpos
BS_Basic< T, cheetah::num_act_joint, 3, 1, 2, 2 > _jpos_trj
Detailed Description
template<typename T>
class JPosInitializer< T >
Definition at line 9 of file JPosInitializer.h.
Constructor & Destructor Documentation
template<typename T> JPosInitializer< T >::JPosInitializer (T end_time)
Definition at line 7 of file JPosInitializer.cpp.
References JPosInitializer< T >::_UpdateParam().
     : _b_first_visit(true),
       _end_time(end_time),
       _curr_time(0.),
       _dt(0.001),
       _ini_jpos(cheetah::num_act_joint) {
   _UpdateParam();
 }
template<typename T > JPosInitializer< T >::~JPosInitializer ()
Definition at line 17 of file JPosInitializer.cpp.
 {}
Member Function Documentation
template<typename T> void JPosInitializer< T >::_UpdateInitial (const LegController< T > * ctrl) private
Definition at line 48 of file JPosInitializer.cpp.
References JPosInitializer< T >::_end_time, JPosInitializer< T >::_ini_jpos, JPosInitializer< T >::_jpos_trj, JPosInitializer< T >::_mid_jpos, JPosInitializer< T >::_target_jpos, LegController< T >::datas, cheetah::num_act_joint, and BS_Basic< T, DIM, DEGREE, NUM_MIDDLE, CONST_LEVEL_INI, CONST_LEVEL_FIN >::SetParam().
{
   T ini[3 * cheetah::num_act_joint];
   T fin[3 * cheetah::num_act_joint];
   T** mid = new T*[1];
   mid[0] = new T[cheetah::num_act_joint];
   for (size_t i(cheetah::num_act_joint); i < 3 * cheetah::num_act_joint; ++i) {
     ini[i] = 0.;
     fin[i] = 0.;
   }
   for (int leg(0); leg < 4; ++leg) {
     for (int jidx(0); jidx < 3; ++jidx) {
       ini[3 * leg + jidx] = ctrl->datas[leg].q[jidx];
       _ini_jpos[3 * leg + jidx] = ctrl->datas[leg].q[jidx];
     }
   }
   for (size_t i(0); i < cheetah::num_act_joint; ++i) {
     fin[i] = _target_jpos[i];
     mid[0][i] = _mid_jpos[i];
   }
   _jpos_trj.SetParam(ini, fin, mid, _end_time);
   delete[] mid[0];
   delete[] mid;
 }
template<typename T > void JPosInitializer< T >::_UpdateParam () private
Definition at line 77 of file JPosInitializer.cpp.
References JPosInitializer< T >::_mid_jpos, and JPosInitializer< T >::_target_jpos.
{
   ParamHandler handler(THIS_COM "config/initial_jpos_ctrl.yaml");
   handler.getVector<T>("target_jpos", _target_jpos);
   handler.getVector<T>("mid_jpos", _mid_jpos);
 }
template<typename T> bool JPosInitializer< T >::IsInitialized (LegController< T > * ctrl)
Definition at line 20 of file JPosInitializer.cpp.
References JPosInitializer< T >::_b_first_visit, JPosInitializer< T >::_curr_time, JPosInitializer< T >::_dt, JPosInitializer< T >::_end_time, JPosInitializer< T >::_jpos_trj, JPosInitializer< T >::_UpdateInitial(), LegController< T >::commands, BS_Basic< T, DIM, DEGREE, NUM_MIDDLE, CONST_LEVEL_INI, CONST_LEVEL_FIN >::getCurvePoint(), cheetah::num_act_joint, cheetah::num_leg, and cheetah::num_leg_joint.
{
   _curr_time += _dt;
   // Initial Setup
   if (_b_first_visit) {
     _UpdateInitial(ctrl);
     _b_first_visit = false;
   }
   // Smooth movement
   if (_curr_time < _end_time) {
     T jpos[cheetah::num_act_joint];
     _jpos_trj.getCurvePoint(_curr_time, jpos);
     // pretty_print(jpos, "jpos_cmd", cheetah::num_act_joint);
     for (size_t leg(0); leg < cheetah::num_leg; ++leg) {
       for (size_t jidx(0); jidx < cheetah::num_leg_joint; ++jidx) {
         ctrl->commands[leg].tauFeedForward[jidx] = 0.;
         ctrl->commands[leg].qDes[jidx] = jpos[3 * leg + jidx];
         ctrl->commands[leg].qdDes[jidx] = 0.;
       }
     }
     return false;
   }
   return true;
 }
Member Data Documentation
template<typename T> bool JPosInitializer< T >::_b_first_visit private
Definition at line 19 of file JPosInitializer.h.
template<typename T> T JPosInitializer< T >::_curr_time private
Definition at line 21 of file JPosInitializer.h.
template<typename T> T JPosInitializer< T >::_dt private
Definition at line 22 of file JPosInitializer.h.
template<typename T> T JPosInitializer< T >::_end_time private
Definition at line 20 of file JPosInitializer.h.
template<typename T> std::vector<T> JPosInitializer< T >::_ini_jpos private
Definition at line 24 of file JPosInitializer.h.
template<typename T> BS_Basic<T, cheetah::num_act_joint, 3, 1, 2, 2> JPosInitializer< T >::_jpos_trj private
Definition at line 28 of file JPosInitializer.h.
template<typename T> std::vector<T> JPosInitializer< T >::_mid_jpos private
Definition at line 26 of file JPosInitializer.h.
template<typename T> std::vector<T> JPosInitializer< T >::_target_jpos private
Definition at line 25 of file JPosInitializer.h.
The documentation for this class was generated from the following files:
JPosInitializer.h
JPosInitializer.cpp